# ClawClock 优化后的 clock.py - 配置常量
"""
ClawClock 常量配置
"""
from config.constants import *

# 窗口配置
WINDOW_WIDTH = WINDOW_WIDTH
WINDOW_HEIGHT = WINDOW_HEIGHT
WINDOW_MIN_WIDTH = WINDOW_MIN_WIDTH
WINDOW_MIN_HEIGHT = WINDOW_MIN_HEIGHT

# 时间配置
REFRESH_INTERVAL = REFRESH_INTERVAL
SECONDARY_REFRESH_INTERVAL = SECONDARY_REFRESH_INTERVAL

# 闹钟配置
MAX_ALARMS = MAX_ALARMS
DEFAULT_ALARM_LABEL = DEFAULT_ALARM_LABEL
SNOOZE_DURATION = SNOOZE_DURATION

# 秒表配置
MAX_LAPS = MAX_LAPS
LAP_FORMAT = LAP_FORMAT

# 倒计时配置
MAX_DURATION_HOURS = MAX_DURATION_HOURS
MAX_DURATION_MINUTES = MAX_DURATION_MINUTES
MAX_DURATION_SECONDS = MAX_DURATION_SECONDS

# 主题配置
DEFAULT_THEME = DEFAULT_THEME
THEME_TYPES = THEME_TYPES

# 呼吸灯配置
BREATH_DEFAULT_ENABLED = BREATH_DEFAULT_ENABLED
BREATH_DEFAULT_MODE = BREATH_DEFAULT_MODE
BREATH_DEFAULT_STYLE = BREATH_DEFAULT_STYLE
BREATH_DEFAULT_FREQUENCY = BREATH_DEFAULT_FREQUENCY
BREATH_DEFAULT_INTENSITY = BREATH_DEFAULT_INTENSITY
BREATH_DEFAULT_ACCELERATE = BREATH_DEFAULT_ACCELERATE
BREATH_DEFAULT_SMOOTH = BREATH_DEFAULT_SMOOTH

# 颜色配置
DEFAULT_COLORS = DEFAULT_COLORS

# 时区配置
TIMEZONE_LIST = TIMEZONE_LIST

# 预设时间
PRESET_TIMES = PRESET_TIMES

# 文件路径
CONFIG_FILE = CONFIG_FILE
ALARMS_FILE = ALARMS_FILE
THEMES_DIR = THEMES_DIR
